<a href="https://colab.research.google.com/github/rebeccalizaverghese/BA-with-Python/blob/main/17_06_df_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [8]:
df=pd.read_excel("/content/Sample - Superstore.xlsx")

In [11]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [17]:
df.Sales.max()

22638.48

In [18]:
df.Sales.min()

0.44399999999999995

In [25]:
df.Sales.mean()

229.8580008304938

In [28]:
df.Sales.count()

9994

In [21]:
df.Sales.sum()

2297200.8603000003

In [33]:
df.groupby('Quantity').max()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Discount,Profit
Quantity,,,,,,,,,,,,,,,,,,,,
1,9988,US-2017-167920,2017-12-29,2018-01-03,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Yonkers,Wisconsin,99301,West,TEC-PH-10004959,Technology,Tables,iOttie HLCRIO102 Car Mount,1270.990,0.8,635.4950
2,9994,US-2017-169551,2017-12-30,2018-01-05,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,York,Wisconsin,99301,West,TEC-PH-10004977,Technology,Tables,netTALK DUO VoIP Telephone Service,4799.984,0.8,1995.9900
3,9990,US-2017-169551,2017-12-30,2018-01-04,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,York,Wisconsin,99207,West,TEC-PH-10004977,Technology,Tables,netTALK DUO VoIP Telephone Service,10499.970,0.8,5039.9856
4,9993,US-2017-168802,2017-12-30,2018-01-04,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,Yuma,Wyoming,98661,West,TEC-PH-10004977,Technology,Tables,netTALK DUO VoIP Telephone Service,13999.960,0.8,6719.9808
5,9989,US-2017-169502,2017-12-29,2018-01-02,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,Yuma,Wisconsin,99301,West,TEC-PH-10004977,Technology,Tables,invisibleSHIELD by ZAGG Smudge-Free Screen Pro...,17499.950,0.8,8399.9760
6,9948,US-2017-167402,2017-12-28,2017-12-31,Standard Class,YS-21880,Yana Sorensen,Home Office,United States,Yuma,Wisconsin,99301,West,TEC-PH-10004922,Technology,Tables,iOttie HLCRIO102 Car Mount,22638.480,0.8,1453.1238
7,9983,US-2017-165344,2017-12-30,2018-01-04,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Yuma,Wisconsin,99207,West,TEC-PH-10004977,Technology,Tables,Zebra GX420t Direct Thermal/Thermal Transfer P...,9099.930,0.8,2400.9657
8,9949,US-2017-158526,2017-12-29,2018-01-05,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Yonkers,Wisconsin,99301,West,TEC-PH-10004531,Technology,Tables,Zipper Ring Binder Pockets,8159.952,0.8,1459.2000
9,9943,US-2017-166688,2017-12-25,2018-01-01,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Wilmington,Wisconsin,99207,West,TEC-PH-10004667,Technology,Tables,netTALK DUO VoIP Telephone Service,5399.910,0.8,2591.9568
10,9985,US-2017-165344,2017-12-04,2017-12-09,Standard Class,VT-21700,Valerie Takahito,Home Office,United States,Tucson,Washington,98226,West,TEC-PH-10004614,Technology,Tables,iKross Bluetooth Portable Keyboard + Cell Phon...,4007.840,0.8,394.2680
11,9896,US-2017-142188,2017-11-28,2017-12-02,Standard Class,TT-21460,Tonja Turnell,Home Office,United States,Vacaville,Wisconsin,98115,West,TEC-PH-10002834,Technology,Storage,Xerox 232,2888.127,0.7,767.2005
12,8871,US-2017-110576,2017-12-01,2017-12-06,Standard Class,XP-21865,Xylona Preis,Home Office,United States,Tulsa,Washington,98270,West,TEC-PH-10002496,Technology,Tables,"Wirebound Message Books, Four 2 3/4 x 5 White ...",3610.848,0.4,561.5640
13,9883,US-2017-147669,2017-12-25,2017-12-30,Standard Class,VP-21760,Victoria Pisteka,Home Office,United States,Woodstock,Washington,98103,West,TEC-PH-10004833,Technology,Tables,Xerox 1952,9892.740,0.8,4946.3700
14,9980,US-2017-155425,2017-12-14,2017-12-18,Standard Class,TG-21640,Trudy Glocke,Home Office,United States,Tucson,Washington,98103,West,TEC-PH-10001557,Technology,Storage,Xerox 1964,1819.860,0.8,510.6360

In [42]:
df.groupby('Ship Mode').count()

,Row ID,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Ship Mode,,,,,,,,,,,,,,,,,,,,
First Class,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538
Same Day,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543
Second Class,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945
Standard Class,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968

In [43]:
df.groupby('State').mean()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
State,,,,,,
Alabama,3997.967213,35994.573770,319.846557,4.196721,0.000000,94.865989
Arizona,4553.017857,85277.348214,157.508933,3.848214,0.303571,-15.303235
Arkansas,5076.250000,72321.816667,194.635500,4.000000,0.000000,66.811452
California,5066.191404,92145.246877,228.729451,3.831584,0.072764,38.171608
Colorado,4379.131868,80295.758242,176.418231,3.807692,0.316484,-35.867351
Connecticut,5419.646341,6475.670732,163.223866,3.426829,0.007317,42.823071
Delaware,5253.854167,19755.250000,285.948635,3.822917,0.006250,103.930988
District of Columbia,1791.800000,20016.000000,286.502000,4.000000,0.000000,105.958930
Florida,5112.937337,33003.198433,233.612815,3.600522,0.299347,-8.875461
Georgia,4802.119565,30899.347826,266.825217,3.831522,0.000000,88.315453
Idaho,6163.190476,83462.333333,208.689810,3.047619,0.085714,39.367767
Illinois,5226.587398,60719.048780,162.939230,3.750000,0.390041,-25.625787
Indiana,4891.073826,46923.503356,359.431946,3.879195,0.000000,123.375411
Iowa,4739.100000,51256.900000,152.658667,3.733333,0.000000,39.460397
Kansas,5223.833333,66824.916667,121.429583,3.083333,0.000000,34.851813
Kentucky,5028.208633,41189.467626,263.250000,3.762590,0.000000,80.573357
Louisiana,4133.928571,70777.357143,219.453095,3.714286,0.000000,52.288150
Maine,5774.750000,4340.625000,158.816250,4.375000,0.000000,56.810775
Maryland,5299.266667,21016.571429,225.766886,4.000000,0.005714,66.963608
Massachusetts,5250.940741,1987.370370,212.106919,3.637037,0.015556,50.262975
Michigan,4706.537255,48455.305882,299.096525,3.709804,0.007059,95.934069
Minnesota,3557.808989,55418.247191,335.541011,3.719101,0.000000,121.608847
Mississippi,4734.018868,39189.113208,203.232830,4.169811,0.000000,59.867475
Missouri,4927.969697,65126.696970,336.441667,3.818182,0.000000,97.518341
Montana,4095.866667,59491.733333,372.623467,3.733333,0.066667,122.221900
Nebraska,5404.842105,68121.421053,196.445526,3.578947,0.000000,53.607742
Nevada,5731.948718,89136.846154,428.951333,4.307692,0.061538,85.045279
New Hampshire,5023.888889,3475.370370,270.093481,4.703704,0.011111,63.203807
New Jersey,5029.653846,7753.338462,275.110092,3.492308,0.004615,75.176260
New Mexico,4493.270270,87609.621622,129.284378,4.081081,0.059459,31.273408
New York,4833.418440,10492.660461,275.599531,3.744681,0.055319,65.637011
North Carolina,4896.293173,28089.895582,223.305880,3.947791,0.283534,-30.083985
North Dakota,5256.571429,58103.000000,131.415714,4.285714,0.000000,32.878529
Ohio,5023.441365,43880.247335,166.861697,3.750533,0.324947,-36.186304
Oklahoma,4978.015152,73683.636364,298.233182,3.742424,0.000000,73.544788
Oregon,5266.096774,97355.846774,140.573790,4.024194,0.288710,-9.600569
Pennsylvania,4716.393526,19063.994889,198.487077,3.667802,0.328620,-26.507598
Rhode Island,5453.303571,2908.535714,404.070643,3.553571,0.021429,130.100523
South Carolina,4621.309524,29287.333333,201.945476,4.095238,0.000000,42.120395
South Dakota,4071.500000,57227.500000,109.630000,3.500000,0.000000,32.902358
Tennessee,5836.836066,37653.409836,167.551219,3.721311,0.291257,-29.189583
Texas,5162.985787,76901.211168,172.779742,3.780711,0.370193,-26.121174
Utah,3651.415094,84195.622642,211.699170,4.132075,0.060377,48.047802
Vermont,8277.181818,5408.000000,811.760909,4.545455,0.000000,204.088936
Virginia,5438.111607,22876.495536,315.342500,3.986607,0.000000,83.026564
Washington,5107.624506,98145.626482,273.994605,3.721344,0.064032,66.013146
West Virginia,8293.750000,26003.000000,302.456000,4.500000,0.075000,46.480400
Wisconsin,5190.736364,53633.672727,291.951000,4.209091,0.000000,76.380004
Wyoming,5870.000000,82001.000000,1603.136000,4.000000,0.200000,100.196000

In [49]:
df.groupby('State').Sales.mean()

State
Alabama                  319.846557
Arizona                  157.508933
Arkansas                 194.635500
California               228.729451
Colorado                 176.418231
Connecticut              163.223866
Delaware                 285.948635
District of Columbia     286.502000
Florida                  233.612815
Georgia                  266.825217
Idaho                    208.689810
Illinois                 162.939230
Indiana                  359.431946
Iowa                     152.658667
Kansas                   121.429583
Kentucky                 263.250000
Louisiana                219.453095
Maine                    158.816250
Maryland                 225.766886
Massachusetts            212.106919
Michigan                 299.096525
Minnesota                335.541011
Mississippi              203.232830
Missouri                 336.441667
Montana                  372.623467
Nebraska                 196.445526
Nevada                   428.951333
New Hampshire            270.093481
New Jersey               275.110092
New Mexico               129.284378
New York                 275.599531
North Carolina           223.305880
North Dakota             131.415714
Ohio                     166.861697
Oklahoma                 298.233182
Oregon                   140.573790
Pennsylvania             198.487077
Rhode Island             404.070643
South Carolina           201.945476
South Dakota             109.630000
Tennessee                167.551219
Texas                    172.779742
Utah                     211.699170
Vermont                  811.760909
Virginia                 315.342500
Washington               273.994605
West Virginia            302.456000
Wisconsin                291.951000
Wyoming                 1603.136000
Name: Sales, dtype: float64

In [50]:
df.groupby('Ship Mode').Quantity.count()

Ship Mode
First Class       1538
Same Day           543
Second Class      1945
Standard Class    5968
Name: Quantity, dtype: int64

In [65]:
df.groupby("Customer Name").Discount.count()

Customer Name
Aaron Bergman          6
Aaron Hawkins         11
Aaron Smayling        10
Adam Bellavance       18
Adam Hart             20
                      ..
Xylona Preis          28
Yana Sorensen         12
Yoseph Carroll         8
Zuschuss Carroll      31
Zuschuss Donatelli     9
Name: Discount, Length: 793, dtype: int64

In [61]:
df.loc[df["Ship Mode"] == "Second Class"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,0.0,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
17,18,CA-2014-167164,2014-05-13,2014-05-15,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,...,84084,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.500,2,0.0,9.9900
18,19,CA-2014-143336,2014-08-27,2014-09-01,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9965,9966,CA-2016-146374,2016-12-05,2016-12-10,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711,East,OFF-PA-10000349,Office Supplies,Paper,Easy-staple paper,4.980,1,0.0,2.3406
9966,9967,CA-2016-146374,2016-12-05,2016-12-10,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711,East,OFF-EN-10004483,Office Supplies,Envelopes,"#10 White Business Envelopes,4 1/8 x 9 1/2",109.690,7,0.0,51.5543
9980,9981,US-2015-151435,2015-09-06,2015-09-09,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.980,1,0.0,22.3548
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [70]:
df.loc[df['Category']== "Office Supplies"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,9983,US-2016-157728,2016-09-22,2016-09-28,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,49505,Central,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",35.560,7,0.0,16.7132
9984,9985,CA-2015-100251,2015-05-17,2015-05-23,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-LA-10003766,Office Supplies,Labels,Self-Adhesive Removable Labels,31.500,10,0.0,15.1200
9985,9986,CA-2015-100251,2015-05-17,2015-05-23,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,55.600,4,0.0,16.1240
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480